package com.airiea.agent.model.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "agents")
public class AgentDAO {
    @DynamoDBHashKey(attributeName = "agent_name")
    @JsonProperty("agent_name")
    String agentName;

    /**
     * Describe the background of the task executor
     */
    @DynamoDBAttribute(attributeName = "agent_role")
    @JsonProperty("agent_role")
    String agentRole;

    @DynamoDBAttribute(attributeName = "agent_goal")
    @JsonProperty("agent_goal")
    String agentGoal;

    @DynamoDBAttribute(attributeName = "ability_name")
    @JsonProperty("ability_name")
    String abilityName;

    @JsonProperty("created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    Date createdDate;

    @JsonProperty("updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    Date updatedDate;
}

